### ISSUE TITLE
有没有比较完整的例子呢

### ISSUE THREAD

**Issue by skating507** [declangao/WordpressReader#1]
比如登录，和本地评论的功能，当然还有自定义文章分类，和获取自定义域。

**Comment by declangao** [comment]
登录没试过，你可以看看WordPress官方的app怎么实现的。
本地评论可以轻易的用JSON API实现，看一下API文档就能明白了，由于本地评论大量spam，所以我才换到Disqus的。
自定义文章分类一直可以支持的啊，我代码里看mainactivity，里面的tab是动态读取分类生成的。
获取custom field也是API支持的，每一个post都有一个叫custom_fields的JSON array。详细用法可以看我第一个commit里获取文章阅读量的代码，这个就是用custom field实现的，不过后来感觉没用就去掉了。
