### ISSUE TITLE
Loading articles...

### ISSUE THREAD

**Issue by ghost** [declangao/WordpressReader#13]
I have a problem, plaicción works perfectly . But at the time of loading / display items . It does not. No it does! Since I do not encounter this problem

![device-2016-03-03-211952](https://cloud.githubusercontent.com/assets/12376645/13508075/c0850700-e185-11e5-9f23-0e5d690b6c79.png)

**Comment by jayhack7** [comment]
I realized that only Wordpress.org websites can use this app. Because Wordpress.com (the free ones) do not support plugins. A Wordpress.org website can use plugins (you need to install the JSON API first)

**Comment by abelini** [comment]
I have the same issue, and I have a self hosted Wordpress. It crashes just after launch and it shows a message at the bottom that says: "Network error. Failed to load articles". By the way, i do have the JSON plugin installed and activated (http://proyecto3.mx/?json=get_category_index)
