### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by skating507** [declangao/WordpressReader#2]
1，能否添加搜索功能，和浏览器，而非要不浏览器；
2，评论比较比较少用，能否改为本地评论；
3，custom post type替换分类，分类单独作为一个页面上展示就可以了。这样可以更多的应用和学习，比较刚学的很多东西不太懂。
非常感谢了～～

**Comment by declangao** [comment]
搜索功能这个我会在今后加入的。
评论的话，我不想换到本地评论，我见过的多数WordPress 网站也都不是用本地评论的，全是Disqus 或是多说之类的第三方评论。
这个App 我设计的就是一个新闻阅读器，所以用的分类。如果想要custom post type 的话，获取内容不难，在URL 里加上post_type 的参数就好了。但是API 没有提供得到有哪些custom post type 的功能。。。

**Comment by declangao** [comment]
搜索功能已经加入
